/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm.fenetres;

import com.sun.mail.smtp.SMTPTransport;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.security.Security;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import modele.Devis;
import modele.DevisContenu;
import modele.Sessions;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import javax.swing.BorderFactory;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.border.Border;

/**
 *
 * @author Travail Ruel
 */
public class EnvoieDevis extends javax.swing.JDialog {
    private Devis devis;
    private Sessions session;
    private String secreteriat;
    /**
     * Creates new form EnvoieDevis
     */
    public EnvoieDevis(java.awt.Frame parent, boolean modal,Sessions session,Devis devis) {
        super(parent, modal);
        this.session=session;
        this.devis=devis;
        this.secreteriat="XXXXXXX@XXXXXX.fr";
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreLabel = new javax.swing.JLabel();
        infoDevisLabel = new javax.swing.JLabel();
        ouvrirLabel = new javax.swing.JLabel();
        btnOuvrir = new javax.swing.JButton();
        envoyerLabel = new javax.swing.JLabel();
        chSecreteriat = new javax.swing.JCheckBox();
        chClient = new javax.swing.JCheckBox();
        btnEnvoyer = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titreLabel.setText("Gestion du Devis");

        infoDevisLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        infoDevisLabel.setForeground(new java.awt.Color(51, 204, 0));
        infoDevisLabel.setText("Votres devis a bien été générer");

        ouvrirLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ouvrirLabel.setText("Voulez vous ouvrir le devis ?");

        btnOuvrir.setText("Ouvrir");
        btnOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOuvrirActionPerformed(evt);
            }
        });

        envoyerLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        envoyerLabel.setText("Voulez vous envoyer le devis ?");

        chSecreteriat.setText("Secretaire");

        chClient.setText("Client");
        chClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chClientActionPerformed(evt);
            }
        });

        btnEnvoyer.setText("Envoyer");
        btnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerActionPerformed(evt);
            }
        });

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoDevisLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ouvrirLabel)
                                .addGap(18, 18, 18)
                                .addComponent(btnOuvrir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(envoyerLabel)
                                .addGap(18, 18, 18)
                                .addComponent(chSecreteriat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnvoyer)))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(titreLabel)
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnFermer)
                                .addGap(19, 19, 19))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreLabel)
                .addGap(34, 34, 34)
                .addComponent(infoDevisLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouvrirLabel)
                    .addComponent(btnOuvrir))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envoyerLabel)
                    .addComponent(chSecreteriat)
                    .addComponent(chClient)
                    .addComponent(btnEnvoyer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnFermer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOuvrirActionPerformed
        try {

            Desktop d = Desktop.getDesktop();
            d.open(new File("devis/devis-"+devis.getNumero()+".pdf"));
        } catch (IOException ex) {
            Logger.getLogger(EnvoieDevis.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnOuvrirActionPerformed
    
    
    private void btnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerActionPerformed
       
        String emailClient = devis.getClient().getEmail();
        int numeroLigneClient = session.getRecupDonnees().recupererLigneModificationClients(this.devis.getClient());
        if(chClient.isSelected()==true&&emailClient.charAt(0)==' '){
            try {
                JOptionPane.showMessageDialog(null,"Le Client n'a pas d'adresse email");
                String email;
                email = (String)JOptionPane.showInputDialog( null, "Entrez l'email :", "Ajout Email", JOptionPane.PLAIN_MESSAGE);
                this.devis.getClient().setEmail(email);
                this.session.getRecupDonnees().enregistrementModificationClients(numeroLigneClient, this.devis.getClient());
            } catch (IOException ex) {
                Logger.getLogger(EnvoieDevis.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(chClient.isSelected()==false&&chSecreteriat.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Veuillez choisir un destinataire");
        }else{
        try {
            Properties props = null;
            Session session = null;
            SMTPTransport transport = null;
            MimeMessage mimeMsg = null;
            String sProtocole = "smtp"; // ou "smtps"
            String sURLServeurSMTP = "smtp.live.com";
            String sNumPort = "587"; // ou 465 pour TLS
            String sUserName = "xxxxx@xxxxxx.xx";
            String sMdp = "xxxxxxx";
            
            props = System.getProperties();
            props.put("mail." + sProtocole + ".host", sURLServeurSMTP);
            props.put("mail." + sProtocole + ".port", sNumPort);
            props.put("mail." + sProtocole + ".auth", "true");
            if( sProtocole.equals("smtp") && sNumPort.equals("587") ) {
                props.put("mail.smtp.starttls.enable", "true");
            }

            Session sessionS = Session.getDefaultInstance(props, 
            new javax.mail.Authenticator(){
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(
                        "xxxxx@xxxxxx.xx", "xxxxxxxx");// Specify the Username and the PassWord
                }
            });
            transport = (SMTPTransport)sessionS.getTransport(sProtocole);
            transport.connect(sURLServeurSMTP, Integer.parseInt(sNumPort), sUserName, sMdp);

            
            /*
            Construire ici son mail
            */
             // Instantiate a message
            Message msg = new MimeMessage(sessionS);

            int numeroDevis = devis.getNumero();
            
            //Set message attributes
            msg.setFrom(new InternetAddress("xxxxx@xxxxxx.xx"));
            InternetAddress[] addressTempo=null;
            if(chClient.isSelected()==true&&chSecreteriat.isSelected()==false){
                InternetAddress[] address = {new InternetAddress(devis.getClient().getEmail())};
                addressTempo=address;
            }else if(chClient.isSelected()==false&&chSecreteriat.isSelected()==true){
                InternetAddress[] address = {new InternetAddress(this.secreteriat)};
                addressTempo=address;
            }else if(chClient.isSelected()==true&&chSecreteriat.isSelected()==true){
                InternetAddress[] address = {new InternetAddress(this.secreteriat),new InternetAddress(devis.getClient().getEmail())};
                addressTempo=address;
            }
            msg.setRecipients(Message.RecipientType.TO, addressTempo);
            msg.setSubject("Toitures Poitevines Devis n°"+numeroDevis);
            msg.setSentDate(new Date());
            //Send the message
            

            
            
            
            
            
                        // Première partie du message
             BodyPart messageBodyPart = new MimeBodyPart();
            messageBodyPart.setText("devis n°"+numeroDevis + " | Nom : "+devis.getClient().getNom()+" | Prenom : "+devis.getClient().getPrenom()+" | Code Postal : "+devis.getClient().getCodePostale()+" | Commune : "+devis.getClient().getCommune()+" | Adresse : "+devis.getClient().getAdresse()+ " | Email : "+devis.getClient().getEmail()+" | Tel : 0"+devis.getClient().getNumero());
            //Ajout de la première partie du message dans un objet Multipart
            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);
            // Partie de la pièce jointe
            messageBodyPart = new MimeBodyPart();

            DataSource source = new FileDataSource("devis/devis-"+numeroDevis+".pdf");
            messageBodyPart.setDataHandler(new DataHandler(source));
            messageBodyPart.setFileName("devis-"+numeroDevis+".pdf");

            //Ajout de la partie pièce jointe
            multipart.addBodyPart(messageBodyPart);
            msg.setContent(multipart);
            Transport.send(msg,msg.getAllRecipients());
            transport.close();
            JOptionPane.showMessageDialog(null,"Message envoyer !");
        } catch (NoSuchProviderException ex) {
            JOptionPane.showMessageDialog(null,"ATTENTION ! Problème l'ors de l'envoi du mail !");
            Logger.getLogger(EnvoieDevis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            JOptionPane.showMessageDialog(null,"ATTENTION ! Problème l'ors de l'envoi du mail !");
            Logger.getLogger(EnvoieDevis.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        }
    }//GEN-LAST:event_btnEnvoyerActionPerformed

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_btnFermerActionPerformed

    private void chClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chClientActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnOuvrir;
    private javax.swing.JCheckBox chClient;
    private javax.swing.JCheckBox chSecreteriat;
    private javax.swing.JLabel envoyerLabel;
    private javax.swing.JLabel infoDevisLabel;
    private javax.swing.JLabel ouvrirLabel;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables
}

