/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm.panneaux;

import ihm.fenetres.FenetrePrincipale;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import modele.Sessions;

/**
 *
 * @author Travail Ruel
 */
public class Accueil extends javax.swing.JPanel {
    private Sessions parents;
    /**
     * Creates new form Accueil
     */
    public Accueil(Sessions parents) {
        this.parents=parents;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconBd = new javax.swing.ImageIcon("bd.png");
        labelIconBd = new javax.swing.JLabel(iconBd);
        iconDevis = new javax.swing.ImageIcon("devis.png");
        labalIconDevis = new javax.swing.JLabel(iconDevis);
        imgParametre = new ImageIcon("parametre.png");
        labelParametre = new javax.swing.JLabel(imgParametre);

        labelIconBd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIconBdMouseClicked(evt);
            }
        });

        labalIconDevis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labalIconDevisMouseClicked(evt);
            }
        });

        labelParametre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelParametreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelIconBd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(labalIconDevis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelParametre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelParametre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labalIconDevis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIconBd, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelIconBdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIconBdMouseClicked
        this.parents.changerAffichage(FenetrePrincipale.Etat.AJOUTERBASE);
    }//GEN-LAST:event_labelIconBdMouseClicked

    private void labalIconDevisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labalIconDevisMouseClicked
        this.parents.changerAffichage(FenetrePrincipale.Etat.DEVIS);
    }//GEN-LAST:event_labalIconDevisMouseClicked

    private void labelParametreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelParametreMouseClicked
        this.parents.changerAffichage(FenetrePrincipale.Etat.PARAMETRE);
    }//GEN-LAST:event_labelParametreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ImageIcon iconDevis;
    private javax.swing.JLabel labalIconDevis;
    private javax.swing.ImageIcon iconBd;
    private javax.swing.JLabel labelIconBd;
    private javax.swing.ImageIcon imgParametre;
    private javax.swing.JLabel labelParametre;
    // End of variables declaration//GEN-END:variables
}
