/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm.panneaux;

import ihm.fenetres.FenetrePrincipale;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modele.Sessions;

/**
 *
 * @author Travail Ruel
 */
public class Parametre extends javax.swing.JPanel {
    private Sessions sessioncourante;
    /**
     * Creates new form Parametre
     */
    public Parametre(Sessions sessioncourante) {
        this.sessioncourante=sessioncourante;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        devisLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        nomTextField = new javax.swing.JTextField();
        siegeLabel = new javax.swing.JLabel();
        siegeTextField = new javax.swing.JTextField();
        cogerantLabel = new javax.swing.JLabel();
        telTextField = new javax.swing.JTextField();
        telLabel = new javax.swing.JLabel();
        cogerantTextField = new javax.swing.JTextField();
        entrepriseLabel = new javax.swing.JLabel();
        informationComplementaireLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationcomplementaireTextArea = new javax.swing.JTextArea();
        valider = new javax.swing.JButton();

        titreLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titreLabel.setText("Parametres");

        devisLabel.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        devisLabel.setText("Devis");

        nomLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomLabel.setText("Nom :");

        try {
            nomTextField.setText(sessioncourante.getRecupDonnees().recupererNomEntreprise());
        } catch (IOException ex) {
            Logger.getLogger(AjouterBase.class.getName()).log(Level.SEVERE, null, ex);
        }
        nomTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTextFieldActionPerformed(evt);
            }
        });

        siegeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siegeLabel.setText("Siege :");

        try{
            siegeTextField.setText(sessioncourante.getRecupDonnees().recupererSiegeEntreprise());
        } catch (IOException ex) {
            Logger.getLogger(AjouterBase.class.getName()).log(Level.SEVERE, null, ex);
        }

        cogerantLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cogerantLabel.setText("Cogerant :");

        try {
            telTextField.setText(sessioncourante.getRecupDonnees().recupererNumeroEntreprise());
        } catch (IOException ex) {
            Logger.getLogger(AjouterBase.class.getName()).log(Level.SEVERE, null, ex);
        }

        telLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telLabel.setText("Tel : ");

        try{
            cogerantTextField.setText(sessioncourante.getRecupDonnees().recupererCoGerant());
        } catch (IOException ex) {
            Logger.getLogger(AjouterBase.class.getName()).log(Level.SEVERE, null, ex);
        }

        entrepriseLabel.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        entrepriseLabel.setText("Entreprise");

        informationComplementaireLabel.setText("informationsComplementaire :");

        informationcomplementaireTextArea.setColumns(20);
        informationcomplementaireTextArea.setRows(5);
        try {
            informationcomplementaireTextArea.setText(sessioncourante.getRecupDonnees().recupererInformationsComplementaire());
        } catch (IOException ex) {
            Logger.getLogger(AjouterBase.class.getName()).log(Level.SEVERE, null, ex);
        }
        jScrollPane1.setViewportView(informationcomplementaireTextArea);

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(siegeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(siegeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cogerantLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cogerantTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nomLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(85, 85, 85)
                                    .addComponent(telLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(entrepriseLabel)
                            .addComponent(devisLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valider))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(informationComplementaireLabel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(titreLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrepriseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomLabel)
                        .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siegeLabel)
                    .addComponent(siegeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cogerantLabel)
                    .addComponent(cogerantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(devisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationComplementaireLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valider)
                .addGap(197, 197, 197))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        try {
            sessioncourante.getSaveDonnees().enregistrerParametres(nomTextField.getText(),telTextField.getText(), siegeTextField.getText(), cogerantTextField.getText(), informationcomplementaireTextArea.getText());
            sessioncourante.changerAffichage(FenetrePrincipale.Etat.ACCUEIL);
        } catch (IOException ex) {
            Logger.getLogger(Parametre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_validerActionPerformed

    private void nomTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cogerantLabel;
    private javax.swing.JTextField cogerantTextField;
    private javax.swing.JLabel devisLabel;
    private javax.swing.JLabel entrepriseLabel;
    private javax.swing.JLabel informationComplementaireLabel;
    private javax.swing.JTextArea informationcomplementaireTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JLabel siegeLabel;
    private javax.swing.JTextField siegeTextField;
    private javax.swing.JLabel telLabel;
    private javax.swing.JTextField telTextField;
    private javax.swing.JLabel titreLabel;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
